Update tree_pairwisedists.py
To resolve:
Traceback (most recent call last):
  File "tree_pairwisedists.py", line 43, in <module>
    with utils.open( args['out_file'] ) as out:
AttributeError: 'module' object has no attribute 'open'

Change to:
    with open(args['out_file'], 'w') as out